### ISSUE TITLE
Chectl server:start command uses old plugin registry env var in configmap

### ISSUE THREAD

**Issue by amisevsk** [che-incubator/chectl#92]
When running `chectl server:start -p minishift -a operator`, the created `che` configmap uses the incorrect plugin registry path:

- `CHE_WORKSPACE_PLUGIN__REGISTRY__URL: 'https://che-plugin-registry.openshift.io/'`

should be 

- `CHE_WORKSPACE_PLUGIN__REGISTRY__URL: 'https://che-plugin-registry.openshift.io/v2'`

As of Che `7.0.0-beta-4.0` this causes workspace starts to fail, since Che attempts to use the current plugin reference spec `publisher/name/version` and the non `v2` registry is incompatible. 

I'm not clear on why this is happening, as the operator [is updated to use `v2`](https://github.com/eclipse/che-operator/blob/9241e2f4120b9a2a999f93c02954f448969a15d4/pkg/deploy/defaults.go#L29)

**Comment by l0rd** [comment]
That's probably because we are using the "old" operator here.

**Comment by l0rd** [comment]
This PR introduced the new operator based on the operator SDK https://github.com/eclipse/che-operator/pull/6

Currently in chectl we are using image `eclipse/che-operator` but we need to change `installer/operator.ts` to behave as the new [operator deploy.sh script](https://github.com/eclipse/che-operator/blob/master/deploy.sh).

**Comment by nickboldt** [comment]
Workaround is: `oc set env dc/che CHE_WORKSPACE_PLUGIN__REGISTRY__URL=https://che-plugin-registry.openshift.io/v3` once your deployment is live.

More: http://divby0.blogspot.com/2019/06/deploying-che-7-to-minishift-with-chectl.html (uses the minishift addon instead of the operator)

**Comment by apupier** [comment]
> Workaround is: `oc set env dc/che CHE_WORKSPACE_PLUGIN__REGISTRY__URL=https://che-plugin-registry.openshift.io/v3` once your deployment is live.

Do you have an idea of the equivalent for Minikube installation?

**Comment by apupier** [comment]
> > Workaround is: `oc set env dc/che CHE_WORKSPACE_PLUGIN__REGISTRY__URL=https://che-plugin-registry.openshift.io/v3` once your deployment is live.
> 
> Do you have an idea of the equivalent for Minikube installation?

for Minikube:
`kubectl edit cm -n che`
then edit yaml to have CHE_WORKSPACE_PLUGIN__REGISTRY__URL=https://che-plugin-registry.openshift.io/v3
`kubectl get pods -n che`
replace XXX with correctname `kubectl delete pod/che-XXXX-XXX -n che`
wait that the new pod is started
enjoy

**Comment by l0rd** [comment]
This issue has been fixed by https://github.com/che-incubator/chectl/pull/179

The issue on minishift is solved as well for users that use latest version of minishift.

**Comment by apupier** [comment]
I tried yesterday locally and I still have the problem with minikube.
I called chectl update just before recreating the Che instance.
I have chectl/0.0.2-6d3894f win32-x64 node-v10.4.1
